
    export const GET_ALL_BATTERIES_REQUEST = "GET_ALL_BATTERIES_REQUEST";  
    export const GET_ALL_BATTERIES_SUCCESS = "GET_ALL_BATTERIES_SUCCESS";
    export const GET_ALL_BATTERIES_FAILURE = "GET_ALL_BATTERIES_FAILURE";
    export const ADD_NEW_BATTERY_REQUEST = "ADD_NEW_BATTERY_REQUEST"    ;
    export const ADD_NEW_BATTERY_SUCCESS = "ADD_NEW_BATTERY_SUCCESS"    ;
    export const ADD_NEW_BATTERY_FAILURE = "ADD_NEW_BATTERY_FAILURE"    ;
    export const ADD_NEW_BATTERY_RESET = "ADD_NEW_BATTERY_RESET"    ;
    export const UPDATE_BATTERY_REQUEST = "UPDATE_BATTERY_REQUEST"      ;
    export const UPDATE_BATTERY_SUCCESS = "UPDATE_BATTERY_SUCCESS"      ;
    export const UPDATE_BATTERY_FAILURE = "UPDATE_BATTERY_FAILURE"      ;
    export const UPDATE_BATTERY_RESET = "UPDATE_BATTERY_RESET"      ;
    export const DELETE_BATTERY_REQUEST = "DELETE_BATTERY_REQUEST"      ;
    export const DELETE_BATTERY_SUCCESS = "DELETE_BATTERY_SUCCESS"      ;
    export const DELETE_BATTERY_FAILURE = "DELETE_BATTERY_FAILURE"      ;
