
export const GET_ALL_CLIENTS_REQUEST = "GET_ALL_CLIENTS_REQUEST";  
export const GET_ALL_CLIENTS_SUCCESS = "GET_ALL_CLIENTS_SUCCESS";
export const GET_ALL_CLIENTS_FAILURE = "GET_ALL_CLIENTS_FAILURE";
export const ADD_NEW_CLIENT_REQUEST = "ADD_NEW_CLIENT_REQUEST"  ;
export const ADD_NEW_CLIENT_SUCCESS = "ADD_NEW_CLIENT_SUCCESS"  ;
export const ADD_NEW_CLIENT_FAILURE = "ADD_NEW_CLIENT_FAILURE"  ;
export const ADD_NEW_CLIENT_RESET = "ADD_NEW_CLIENT_RESET"      ;
export const UPDATE_CLIENT_REQUEST = "UPDATE_CLIENT_REQUEST"    ;
export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS"    ;
export const UPDATE_CLIENT_FAILURE = "UPDATE_CLIENT_FAILURE"    ;
export const UPDATE_CLIENT_RESET = "UPDATE_CLIENT_RESET"        ;
export const DELETE_CLIENT_REQUEST = "DELETE_CLIENT_REQUEST"    ;
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS"    ;
export const DELETE_CLIENT_FAILURE = "DELETE_CLIENT_FAILURE"    ;
