
export const GET_ALL_INVERTERS_REQUEST = "GET_ALL_INVERTERS_REQUEST";
export const GET_ALL_INVERTERS_SUCCESS = "GET_ALL_INVERTERS_SUCCESS";
export const GET_ALL_INVERTERS_FAILURE = "GET_ALL_INVERTERS_FAILURE";
export const ADD_NEW_INVERTER_REQUEST = "ADD_NEW_INVERTER_REQUEST";
export const ADD_NEW_INVERTER_SUCCESS = "ADD_NEW_INVERTER_SUCCESS";
export const ADD_NEW_INVERTER_FAILURE = "ADD_NEW_INVERTER_FAILURE";
export const UPDATE_INVERTER_REQUEST = "UPDATE_INVERTER_REQUEST";
export const UPDATE_INVERTER_SUCCESS = "UPDATE_INVERTER_SUCCESS";
export const UPDATE_INVERTER_FAILURE = "UPDATE_INVERTER_FAILURE";
export const DELETE_INVERTER_REQUEST = "DELETE_INVERTER_REQUEST";
export const DELETE_INVERTER_SUCCESS = "DELETE_INVERTER_SUCCESS";
export const DELETE_INVERTER_FAILURE = "DELETE_INVERTER_FAILURE";
