
export const GET_ALL_SOLARS_REQUEST = "GET_ALL_SOLARS_REQUEST";
export const GET_ALL_SOLARS_SUCCESS = "GET_ALL_SOLARS_SUCCESS";
export const GET_ALL_SOLARS_FAILURE = "GET_ALL_SOLARS_FAILURE";
export const ADD_NEW_SOLAR_REQUEST = "ADD_NEW_SOLAR_REQUEST";
export const ADD_NEW_SOLAR_SUCCESS = "ADD_NEW_SOLAR_SUCCESS";
export const ADD_NEW_SOLAR_FAILURE = "ADD_NEW_SOLAR_FAILURE";
export const UPDATE_SOLAR_REQUEST = "UPDATE_SOLAR_REQUEST";
export const UPDATE_SOLAR_SUCCESS = "UPDATE_SOLAR_SUCCESS";
export const UPDATE_SOLAR_FAILURE = "UPDATE_SOLAR_FAILURE";
export const DELETE_SOLAR_REQUEST = "DELETE_SOLAR_REQUEST";
export const DELETE_SOLAR_SUCCESS = "DELETE_SOLAR_SUCCESS";
export const DELETE_SOLAR_FAILURE = "DELETE_SOLAR_FAILURE";
