
    export const GET_ALL_SYSTEMS_REQUEST = "GET_ALL_SYSTEMS_REQUEST";  
    export const GET_ALL_SYSTEMS_SUCCESS = "GET_ALL_SYSTEMS_SUCCESS";
    export const GET_ALL_SYSTEMS_FAILURE = "GET_ALL_SYSTEMS_FAILURE";
    export const ADD_NEW_SYSTEM_REQUEST = "ADD_NEW_SYSTEM_REQUEST"    ;
    export const ADD_NEW_SYSTEM_SUCCESS = "ADD_NEW_SYSTEM_SUCCESS"    ;
    export const ADD_NEW_SYSTEM_FAILURE = "ADD_NEW_SYSTEM_FAILURE"    ;
    export const UPDATE_SYSTEM_REQUEST = "UPDATE_SYSTEM_REQUEST"      ;
    export const UPDATE_SYSTEM_SUCCESS = "UPDATE_SYSTEM_SUCCESS"      ;
    export const UPDATE_SYSTEM_FAILURE = "UPDATE_SYSTEM_FAILURE"      ;
    export const DELETE_SYSTEM_REQUEST = "DELETE_SYSTEM_REQUEST"      ;
    export const DELETE_SYSTEM_SUCCESS = "DELETE_SYSTEM_SUCCESS"      ;
    export const DELETE_SYSTEM_FAILURE = "DELETE_SYSTEM_FAILURE"      ;


    export const UPDATE_SYSTEM_RESET = "UPDATE_SYSTEM_RESET";
export const ADD_NEW_SYSTEM_RESET = "ADD_NEW_SYSTEM_RESET"  ;